export const FETCH_GROUP_DATA = 'FETCH_GROUP_DATA';
export const SAVE_GROUP_DATA = 'SAVE_GROUP_DATA';
export const SAVE_AUTO_FILL_DATA = 'SAVE_AUTO_FILL_DATA';

export const FETCH_GALLERY_DATA = 'FETCH_GALLERY_DATA';
export const SAVE_GALLERY_DATA = 'SAVE_GALLERY_DATA';

export const SAVE_GROUP_NOT_FOUND = 'SAVE_GROUP_NOT_FOUND';
